# Generated by Django 5.0.7 on 2024-08-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('class_time', models.IntegerField()),
                ('class_capacity', models.IntegerField()),
                ('class_name', models.CharField(max_length=50)),
                ('class_lecture', models.CharField(max_length=50)),
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_rep', models.CharField(max_length=50)),
                ('class_description', models.TextField()),
                ('class_attendance', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('schedule', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
