# Generated by Django 5.0.7 on 2024-08-13 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('classperiods', '0001_initial'),
        ('courses', '0002_rename_courses_instuctor_courses_courses_instructor_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classperiod',
            name='student_id',
        ),
        migrations.AddField(
            model_name='classperiod',
            name='classroom',
            field=models.ForeignKey(default='Lovelace', on_delete=django.db.models.deletion.CASCADE, to='classes.classroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classperiod',
            name='teacher',
            field=models.ForeignKey(default='Linda', on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='classperiod',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
    ]
