# Generated by Django 5.0.7 on 2024-08-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_age', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_description', models.TextField()),
                ('teacher_occupation', models.CharField(max_length=50)),
                ('teacher_salary', models.IntegerField()),
                ('teacher_hobby', models.CharField(max_length=50)),
                ('teacher_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('classes', models.ManyToManyField(related_name='teachers', to='classes.classroom')),
            ],
        ),
    ]
