# Generated by Django 5.0.7 on 2024-08-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courses_name', models.CharField(max_length=20)),
                ('courses_id', models.AutoField(primary_key=True, serialize=False)),
                ('courses_code', models.SmallIntegerField()),
                ('courses_instructor', models.CharField(max_length=20)),
                ('courses_assignment', models.CharField(max_length=20)),
                ('courses_level', models.CharField(max_length=20)),
                ('courses_department', models.CharField(max_length=20)),
                ('courses_syllabus', models.CharField(max_length=20)),
                ('courses_exams', models.CharField(max_length=20)),
                ('courses_term', models.CharField(max_length=10)),
            ],
        ),
    ]
